### ISSUE TITLE
Documentation assumes both the presence and familiarity with ruby, rubygems, foreman, etc

### ISSUE THREAD

**Issue by taxilian** [MongoHQ/newrelic-mongodb-agent#1]
I'm muddling through and just about have it figured out, I think, but the steps should really mention that you need to have ruby and rubygems installed and then include steps to install the gems and foreman.

**Comment by taxilian** [comment]
Update: I am not able to get it to run on CentOS 6.3.  I have installed ruby-devel and rubygems with yum and installed bundle, bundler, and foreman with gem install. I then updated the gemfile to specify an https:// instead of git@ address for the repo and bundle install succeeds with no errors but one warning:

```
newrelic_plugin at /home/richard/.bundler/ruby/1.8/newrelic_plugin-913177005ae5 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["README.rdoc"] are not files
```

When I try to run either with "foreman start" or "bundle exec foreman start" I get this:

```
[richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ bundle exec foreman start
10:56:30 mongodb.1 | started with pid 13832
10:56:30 mongodb.1 | /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/source/git.rb:177:in `rescue in load_spec_files': https://github.com/newrelic-platform/newrelic_plugin.git (at release) is not checked out. Please run `bundle install` (Bundler::GitError)
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/source/git.rb:175:in `load_spec_files'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/source/path.rb:86:in `local_specs'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/source/git.rb:150:in `specs'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/lazy_specification.rb:52:in `__materialize__'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:88:in `block in materialize'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:159:in `specs_for'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:148:in `requested_specs'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/environment.rb:18:in `requested_specs'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:13:in `setup'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler.rb:120:in `setup'
10:56:30 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
10:56:30 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
10:56:30 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
10:56:31 mongodb.1 | exited with code 1
10:56:31 system    | sending SIGTERM to all processes
[richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ foreman start
10:56:44 mongodb.1 | started with pid 13840
10:56:44 mongodb.1 | /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)
10:56:44 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
10:56:44 mongodb.1 |    from mongodb_agent.rb:3:in `<main>'
10:56:44 mongodb.1 | exited with code 1
10:56:44 system    | sending SIGTERM to all processes
```

**Comment by Winslett** [comment]
I have updated the Readme.md to reflect the recommendations you have posed.  @taxilian did you run `bundle install` prior to running `bundle exec foreman start`?  I added that instruction item to the README.md.

**Comment by taxilian** [comment]
Tried it again using ~/.gems for GEM_HOME:

```
[richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ export GEM_HOME=~/.gems
[richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ bundle install
Fetching gem metadata from http://rubygems.org/.........
Fetching gem metadata from http://rubygems.org/..
Fetching https://github.com/newrelic-platform/newrelic_plugin.git
remote: Counting objects: 281, done.
remote: Compressing objects: 100% (145/145), done.
remote: Total 281 (delta 131), reused 278 (delta 130)
Receiving objects: 100% (281/281), 47.40 KiB, done.
Resolving deltas: 100% (131/131), done.
Using bson (1.8.2) 
Using bson_ext (1.8.2) 
Using dotenv (0.7.0) 
Using multipart-post (1.2.0) 
Using faraday (0.8.7) 
Using thor (0.18.1) 
Using foreman (0.63.0) 
Using json (1.8.0) 
Using mongo (1.8.2) 
Using newrelic_plugin (1.0.1) from https://github.com/newrelic-platform/newrelic_plugin.git (at release) 
newrelic_plugin at /home/richard/.gems/bundler/gems/newrelic_plugin-913177005ae5 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["README.rdoc"] are not files

Using bundler (1.3.5) 
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
[richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ foreman start
15:34:56 mongodb.1 | started with pid 15421
15:34:56 mongodb.1 | /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)
15:34:56 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
15:34:56 mongodb.1 |    from mongodb_agent.rb:3:in `<main>'
15:34:56 mongodb.1 | exited with code 1
15:34:56 system    | sending SIGTERM to all processes
[richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ bundle exec foreman start
15:35:04 mongodb.1 | started with pid 15426
15:35:05 mongodb.1 | /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find bson-1.8.2 in any of the sources (Bundler::GemNotFound)
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:159:in `specs_for'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:148:in `requested_specs'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/environment.rb:18:in `requested_specs'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:13:in `setup'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler.rb:120:in `setup'
15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
15:35:05 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
15:35:05 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
15:35:05 mongodb.1 | exited with code 1
15:35:05 system    | sending SIGTERM to all processes
```

**Comment by Winslett** [comment]
Try pulling the latest--or looking at the new Gemfile. New Relic released
the plugin SDK as a gem.

On Wednesday, June 19, 2013, Richard Bateman wrote:

> Tried it again using ~/.gems for GEM_HOME:
> 
> [richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ export GEM_HOME=~/.gems
> [richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ bundle install
> Fetching gem metadata from http://rubygems.org/.........
> Fetching gem metadata from http://rubygems.org/..
> Fetching https://github.com/newrelic-platform/newrelic_plugin.git
> remote: Counting objects: 281, done.
> remote: Compressing objects: 100% (145/145), done.
> remote: Total 281 (delta 131), reused 278 (delta 130)
> Receiving objects: 100% (281/281), 47.40 KiB, done.
> Resolving deltas: 100% (131/131), done.
> Using bson (1.8.2)
> Using bson_ext (1.8.2)
> Using dotenv (0.7.0)
> Using multipart-post (1.2.0)
> Using faraday (0.8.7)
> Using thor (0.18.1)
> Using foreman (0.63.0)
> Using json (1.8.0)
> Using mongo (1.8.2)
> Using newrelic_plugin (1.0.1) from https://github.com/newrelic-platform/newrelic_plugin.git (at release)
> newrelic_plugin at /home/richard/.gems/bundler/gems/newrelic_plugin-913177005ae5 did not have a valid gemspec.
> This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
> The validation message from Rubygems was:
>   ["README.rdoc"] are not files
> 
> Using bundler (1.3.5)
> Your bundle is complete!
> Use `bundle show [gemname]` to see where a bundled gem is installed.
> [richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ foreman start
> 15:34:56 mongodb.1 | started with pid 15421
> 15:34:56 mongodb.1 | /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)
> 15:34:56 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
> 15:34:56 mongodb.1 |    from mongodb_agent.rb:3:in `<main>'
> 15:34:56 mongodb.1 | exited with code 1
> 15:34:56 system    | sending SIGTERM to all processes
> [richard@hamhobby newrelic-mongodb-agent-2.4.4-0]$ bundle exec foreman start
> 15:35:04 mongodb.1 | started with pid 15426
> 15:35:05 mongodb.1 | /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:92:in`block in materialize': Could not find bson-1.8.2 in any of the sources (Bundler::GemNotFound)
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in`materialize'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:159:in`specs_for'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/definition.rb:148:in `requested_specs'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/environment.rb:18:in`requested_specs'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/runtime.rb:13:in `setup'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler.rb:120:in`setup'
> 15:35:05 mongodb.1 |    from /usr/lib/ruby/gems/1.8/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
> 15:35:05 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
> 15:35:05 mongodb.1 |    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
> 15:35:05 mongodb.1 | exited with code 1
> 15:35:05 system    | sending SIGTERM to all processes
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MongoHQ/newrelic-mongodb-agent/issues/1#issuecomment-19716841
> .

## 

Christopher Winslett

mobile: 205-924-3472
skype: christopherwinslett

**Comment by Winslett** [comment]
@taxilian, I am closing this issue.  Please respond, and I will reopen.  Thank you.
