### ISSUE TITLE
Use a public github url in the Gemfile

### ISSUE THREAD

**Issue by parrish** [MongoHQ/newrelic-mongodb-agent#2]
Should be
`gem "newrelic_plugin", :git => "git://github.com/newrelic-platform/newrelic_plugin.git", :branch => 'release'`

**Comment by taxilian** [comment]
It would probably be better to use the https url since some firewalls block the git:// protocol

**Comment by Winslett** [comment]
Done & done.  Thank you for the great recommendations.
