### ISSUE TITLE
Memory usage Units

### ISSUE THREAD

**Issue by AlanVerbner** [MongoHQ/newrelic-mongodb-agent#5]
Hi, how are you?

We have recently installed the plugin and there is something strange with Memory Stats. In the dashboard units are in bytes but the mongo doc [1](http://docs.mongodb.org/manual/reference/command/serverStatus/) says that those values are returned in MB.

![screenshot from 2013-06-26 15 02 17](https://f.cloud.github.com/assets/3750504/711108/e165bf56-de8a-11e2-8e16-88e1dadea3ec.png)

Thanks!

**Comment by Winslett** [comment]
Alan, please see the change to the agent to normalize mb to bytes.  I chose this route to minimize changes to the New Relic dashboard.

Suitable?

**Comment by AlanVerbner** [comment]
Sure...works for us...

Thank you very much!
