### ISSUE TITLE
Link is giving a 404 page not found HELP!

### ISSUE THREAD

**Issue by mthomasHMA** [MongoHQ/newrelic-mongodb-agent#7]
Base Installation and Configuration

Prior to installation, you will need to configure Ruby and Gems with foreman. There are

Download the latest release from (https://github.com/MongoHQ/newrelic_mongodb_extension/tags)  This link is giving a 404 page not found.  So I'm stuck here not Ruby expert...

**Comment by mthomasHMA** [comment]
Anyone???

**Comment by Winslett** [comment]
Hello.  I've just made an update to the README for the proper URL.

**Comment by mthomasHMA** [comment]
Quick question for you Will this plugin use SSL to connect to a MongoDB with SSL enable?

**Comment by Winslett** [comment]
I've not tested it with SSL.  If you have it available, will you give it a quick test?

**Comment by mthomasHMA** [comment]
It does not work!!

**Comment by mthomasHMA** [comment]
See issue #8
